[colors.bright]
black = "0x808080"
blue = "0x6699FF"
cyan = "0x66FFFF"
green = "0x66FF99"
magenta = "0xFF66FF"
red = "0xFF6699"
white = "0xFFFFFF"
yellow = "0xFFFF66"

[colors.normal]
black = "0x000000"
blue = "0x3366FF"
cyan = "0x00FFFF"
green = "0x33FF66"
magenta = "0xFF33FF"
red = "0xFF3366"
white = "0xFFFFFF"
yellow = "0xFFFF00"

[colors.primary]
background = "#01012b"
foreground = "#d1f7ff"

[font]
size = 14

[font.bold]
family = "UbuntuMono Nerd Font"

[font.italic]
family = "UbuntuMono Nerd Font"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
opacity = 0.85

[window.padding]
x = 5
y = 5
